# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindBuddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym', models.CharField(choices=[(b'Wooden', b'John Wooden Center'), (b'Bfit', b'Bruin Fitness Center'), (b'LA', b'LA Fitnes')], max_length=6)),
                ('time', models.CharField(choices=[(b'0', b'06:00 AM'), (b'1', b'06:30 AM'), (b'2', b'07:00 AM'), (b'3', b'07:30 AM'), (b'4', b'08:00 AM'), (b'5', b'08:30 AM'), (b'6', b'09:00 AM'), (b'7', b'09:30 AM'), (b'8', b'10:00 AM'), (b'9', b'10:30 AM'), (b'10', b'11:00 AM'), (b'11', b'11:30 AM'), (b'12', b'12:00 AM'), (b'13', b'12:30 AM'), (b'11', b'01:00 PM'), (b'12', b'01:30 PM'), (b'13', b'02:00 PM'), (b'14', b'02:30 PM'), (b'15', b'03:00 PM'), (b'16', b'03:30 PM'), (b'17', b'04:00 PM'), (b'18', b'04:30 PM'), (b'19', b'05:00 PM'), (b'20', b'05:30 PM'), (b'21', b'06:00 PM'), (b'22', b'06:30 PM'), (b'23', b'07:00 PM'), (b'24', b'07:30 PM'), (b'25', b'08:00 PM'), (b'26', b'08:30 PM'), (b'27', b'09:00 PM'), (b'28', b'09:30 PM'), (b'29', b'10:00 PM'), (b'30', b'10:30 PM'), (b'31', b'11:00 PM'), (b'32', b'11:30 PM')], max_length=2)),
                ('username', models.CharField(default='lol')),
                ('email', models.EmailField(default='lol@gmail.com')),
            ],
        ),
    ]
