# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_findbuddy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findbuddy',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
